Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: helloworld.App
      CodeUri: D:\workspace\say-hello-amazon-function\HelloWorldFunction
      Runtime: java11
      Architectures:
        - x86_64